name: Create ISO release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install xorriso grub-pc-bin mtools && cargo install bootimage

    - name: Set dependencies
      run: rustup target add x86_64-unknown-none && rustup update && rustup override set nightly && rustup component add llvm-tools-preview

    - name: Additional settings
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

    - name: Build Kernel
      run: cargo build --release && cargo bootimage --release

    - name: Create grub.cfg
      run: |
        mkdir -p iso/boot/grub
        echo 'set timeout=0' > iso/boot/grub/grub.cfg
        echo 'set default=0' >> iso/boot/grub/grub.cfg
        echo '' >> iso/boot/grub/grub.cfg
        echo 'menuentry "PyPro OS" {' >> iso/boot/grub/grub.cfg
        echo '    multiboot2 /boot/bootimage-pypro_os.bin' >> iso/boot/grub/grub.cfg
        echo '    boot' >> iso/boot/grub/grub.cfg
        echo '}' >> iso/boot/grub/grub.cfg

    - name: Copy bootimage to ISO directory
      run: cp target/x86_64-os/release/bootimage-pypro_os.bin iso/boot/

    - name: Create ISO image
      run: grub-mkrescue -o iso/PyPro-OS.iso iso

    - name: Compress ISO image to ZIP
      run: zip -9 -j iso/PyPro-OS.zip iso/PyPro-OS.iso

    - name: Upload ZIP to GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: iso/PyPro-OS.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
